### PR TITLE
Escape asterisk in regular expression

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by DavyLandman** [comment]
Thanks!

**Comment by ahmadsalim** [comment]
Thanks! I believe this actually closes #14 .

**Comment by pchaigno** [comment]
@ahmadsalim Hm, now I see I should have used a double backslash...

**Comment by ahmadsalim** [comment]
@pchaigno You are welcome to make a new PR that fixes this 😄.

**Comment by DavyLandman** [comment]
Thanks Ahmed, next time I'll leave it open for you to review.

**Comment by ahmadsalim** [comment]
@DavyLandman Sure, thanks 😄

**Pull request merged**
