### PR TITLE
Fixed regex literals and tags, Added concrete syntax highlighting

### PR DESCRIPTION
**Pull request by ahmadsalim**

### CODE REVIEW

**Comment by ahmadsalim** [comment]
You can see the effects of concrete syntax highlighting here:
[Concrete syntax highlighting](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2Fd937d1c14a1e871c12f56c43ea13dec93af696cc%2FRascal.tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=module+Analyze%0D%0A%0D%0Aimport+Syntax%3B%0D%0A%0D%0Aset%5BId%5D+unreachable%28Machine+m%29+%7B%0D%0A++r+%3D+%7B+%3Cq1%2Cq2%3E+%7C+%28State%29%60state+%3CId+q1%3E+%3CTrans*+ts%3E%60+%3C-+m.states%2C+%0D%0A%09%09%09%09++%28Trans%29%60%3CId+_%3E%3A+%3CId+q2%3E%60+%3C-+ts+%7D%2B%3B%0D%0A++qs+%3D+%5B+q.name+%7C+%2FState+q+%3A%3D+m+%5D%3B%0D%0A++return+%7B+q+%7C+q+%3C-+qs%2C+q+notin+r%5Bqs%5B0%5D%5D+%7D%3B%0D%0A%7D)

**Comment by PaulKlint** [comment]
Looks very good. I tried varies snippets and works well, thanks.

Below is an example that surprises me: (string literals like `"template_open"` are not highlighted in red, while they are in other contexts). Any clue?
```
private MuExp translateStringLiteral(s: (StringLiteral) `<PreStringChars pre> <Expression expression> <StringTail tail>`) {
    preIndent = computeIndent(pre);
    return muBlock( [ muCallPrim3("template_open", translatePreChars(pre), pre@\loc),
    				  *translateExpInStringLiteral(preIndent, expression),
    				  *translateTail(preIndent, tail),
    				  muCallPrim3("template_close", [], tail@\loc)
					]   );
}
```

**Comment by ahmadsalim** [comment]
@PaulKlint Thanks. Hmm, I might have been to general in scope for the lexical `[]` so it also apparently included list literals. I will try and see how to fix this.

**Comment by PaulKlint** [comment]
Here is another one: `int n` versus `list[int] n`. In the former `int` is green in the latter it is not. Is there a reason for this?

**Comment by ahmadsalim** [comment]
Yeah, so the major issue is that `[]` seems to have a different meaning when it's inside `lexical` or `syntax` than when it's outside. I have to figure out a nice way to capture this property.

This is because e.g. `[/bla/]` is a list containing a regex in a normal context, whereas it is something which expects any of the characters `/` `b` `l` or `a` in a lexical context). 
The current way is that it treats all `[]` uniformly as lexical contexts (if it doesn't it will ruin the highlighting elsewhere in the grammar files).

**Comment by ahmadsalim** [comment]
It's my first time writing a TextMate grammar, so it's taking me some time to figure out how to do these things correctly.

**Comment by PaulKlint** [comment]
This has been on our list for a long time since we are no experts on this either. I can imagine that some more regexp fiddling is needed here and that it is not so simple to figure out what these cooperation regents do precisely.

Since I find your highlighter so good (on par or even better than our Eclipse one a I would say) I am doing more experiments and will report surprises here (take this as a compliment, its intended to make this really good!).

Here is another one where a comment is missed:
```
// comment 1

n = 1;  // comment 3
l = [1, // comment 3: non highlighted
     2, 
     3];
```

**Comment by ahmadsalim** [comment]
Great, thank you for the examples and the comments!
I will take a look at fixing this tomorrow, I think I have an idea how to proceed.

**Pull request merged**
